name: ðŸš€ 1. Deploy to Stagging
on:
  push:
    branches:
      - dev_waqar
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to Stagging
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: ðŸ“‚ Sync files to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: "ftp.jbfreshchicken.com"
          username: "u442793684.ims"
          password: "AAaa11@@AAopen2code.com"
          port: "21"
          server-dir: /